name: Auto_Grab_stock_data

on:
  schedule:
    - cron: '5 15 * * 1-5'  # 周一到周五的下午 15:05 执行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt  # 如果你有依赖项，可以使用 requirements.txt

    - name: Run Python script
      run: python Auto_Grab_stock_data.py  # 执行指定的 Python 脚本

    - name: Check if historical_data directory exists and output its contents
      run: |
        if [ -d "historical_data" ]; then
          echo "Directory exists"
          ls -R historical_data  # 输出目录内容以确认生成的文件
        else
          echo "Directory does not exist"
          exit 1
        fi

    - name: Commit and push historical_data
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add historical_data/
        git commit -m "Update historical data" || echo "No changes to commit"
        git push origin main
